from django import forms

from .models import CourseContent

class CourseContentForm(forms.ModelForm):
    class Meta:
        model=CourseContent
        fields = "__all__"  # all fields except autogenerated
        exclude = {"faculty, course"}  # to exclude displaying password field, , "qualification" to add it



