# Generated by Django 5.0 on 2023-12-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='contentimage',
            field=models.FileField(upload_to='coursecontent/'),
        ),
    ]
