# Generated by Django 5.0 on 2024-02-02 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('facultyapp', '0002_alter_coursecontent_contentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ay', models.CharField(max_length=100)),
                ('yr', models.IntegerField()),
                ('sem', models.CharField()),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.faculty')),
            ],
        ),
    ]
