# Generated by Django 5.0 on 2024-02-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0003_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cc',
            name='post',
            field=models.IntegerField(choices=[('0', 'ZERO'), ('1', 'ONE')], default=0),
        ),
    ]
