# Generated by Django 5.0 on 2024-02-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0004_cc_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cc',
            name='post',
            field=models.IntegerField(default=0),
        ),
    ]
