# Generated by Django 5.0 on 2024-02-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0005_alter_cc_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fid', models.BigIntegerField()),
                ('sid', models.CharField()),
                ('ay', models.CharField(max_length=100)),
                ('yr', models.IntegerField()),
                ('sem', models.CharField(max_length=50)),
                ('cid', models.IntegerField()),
                ('cc', models.CharField(max_length=50)),
                ('sec', models.IntegerField()),
                ('sem1', models.FloatField()),
                ('sem2', models.FloatField()),
                ('lab1', models.FloatField()),
                ('quiz1', models.FloatField()),
                ('quiz2', models.FloatField()),
                ('quiz3', models.FloatField()),
                ('quiz4', models.FloatField()),
                ('semend', models.FloatField()),
                ('labend', models.FloatField()),
                ('grade_points', models.FloatField()),
                ('grade', models.CharField()),
            ],
            options={
                'db_table': 'internals_table',
            },
        ),
        migrations.AlterField(
            model_name='cc',
            name='cc',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='cc',
            name='fid',
            field=models.BigIntegerField(),
        ),
    ]
