# Generated by Django 5.0 on 2024-02-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0006_internals_alter_cc_cc_alter_cc_fid'),
    ]

    operations = [
        migrations.AddField(
            model_name='internals',
            name='dept',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
