# Generated by Django 5.0 on 2024-02-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0007_internals_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internals',
            name='grade',
            field=models.CharField(default='F'),
        ),
    ]
