# Generated by Django 5.0 on 2024-05-27 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_student_cur_yr'),
        ('facultyapp', '0008_alter_internals_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hd', models.FileField(upload_to='handout/')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.faculty')),
            ],
            options={
                'db_table': 'handoutposting',
            },
        ),
    ]
