# Generated by Django 5.0 on 2024-05-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0009_handout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internals',
            name='sid',
            field=models.BigIntegerField(),
        ),
    ]
