# Generated by Django 5.0 on 2023-12-27 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegHistoryM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.CharField()),
                ('sname', models.CharField()),
                ('sprogram', models.CharField()),
                ('sdept', models.CharField()),
                ('say', models.CharField()),
                ('syr', models.IntegerField()),
                ('ssem', models.CharField()),
                ('s1', models.CharField()),
                ('f1', models.CharField()),
                ('s2', models.CharField()),
                ('f2', models.CharField()),
                ('s3', models.CharField()),
                ('f3', models.CharField()),
                ('s4', models.CharField(blank=True, null=True)),
                ('f4', models.CharField(blank=True, null=True)),
                ('s5', models.CharField(blank=True, null=True)),
                ('f5', models.CharField(blank=True, null=True)),
                ('s6', models.CharField(blank=True, null=True)),
                ('f6', models.CharField(blank=True, null=True)),
                ('s7', models.CharField(blank=True, null=True)),
                ('f7', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reg_history',
            },
        ),
        migrations.CreateModel(
            name='RegM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE')])),
                ('ay', models.CharField(max_length=10)),
                ('yr', models.IntegerField()),
                ('sem', models.CharField(choices=[('ODD', 'ODD'), ('EVEN', 'EVEN')])),
                ('c1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_c1', to='adminapp.course')),
                ('c2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_c2', to='adminapp.course')),
                ('c3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_c3', to='adminapp.course')),
                ('c4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_c4', to='adminapp.course')),
                ('c5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_c5', to='adminapp.course')),
                ('c6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_c6', to='adminapp.course')),
                ('c7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_c7', to='adminapp.course')),
                ('f11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_f11', to='adminapp.facultycoursemapping')),
                ('f12', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_f12', to='adminapp.facultycoursemapping')),
                ('f13', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_f13', to='adminapp.facultycoursemapping')),
                ('f21', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_f21', to='adminapp.facultycoursemapping')),
                ('f22', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_f22', to='adminapp.facultycoursemapping')),
                ('f23', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_f23', to='adminapp.facultycoursemapping')),
                ('f31', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_f31', to='adminapp.facultycoursemapping')),
                ('f32', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_f32', to='adminapp.facultycoursemapping')),
                ('f33', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_f33', to='adminapp.facultycoursemapping')),
                ('f41', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_f41', to='adminapp.facultycoursemapping')),
                ('f42', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_f42', to='adminapp.facultycoursemapping')),
                ('f43', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_f43', to='adminapp.facultycoursemapping')),
                ('f51', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_f51', to='adminapp.facultycoursemapping')),
                ('f52', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_f52', to='adminapp.facultycoursemapping')),
                ('f53', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_f53', to='adminapp.facultycoursemapping')),
                ('f61', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_f61', to='adminapp.facultycoursemapping')),
                ('f62', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_f62', to='adminapp.facultycoursemapping')),
                ('f63', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_f63', to='adminapp.facultycoursemapping')),
                ('f71', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_f71', to='adminapp.facultycoursemapping')),
                ('f72', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_f72', to='adminapp.facultycoursemapping')),
                ('f73', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_f73', to='adminapp.facultycoursemapping')),
            ],
            options={
                'db_table': 'academic_reg',
            },
        ),
    ]
