# Generated by Django 5.0 on 2023-12-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reghistorym',
            name='f1',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='f2',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='f3',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='f4',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='f5',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='f6',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='f7',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
