# Generated by Django 5.0 on 2023-12-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0002_alter_reghistorym_f1_alter_reghistorym_f2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reghistorym',
            name='cc1',
            field=models.CharField(default='21CS3012'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reghistorym',
            name='cc2',
            field=models.CharField(default='21CS302'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reghistorym',
            name='cc3',
            field=models.CharField(default='21CS302'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reghistorym',
            name='cc4',
            field=models.CharField(default='21CS302'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reghistorym',
            name='cc5',
            field=models.CharField(default='21CS302'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reghistorym',
            name='cc6',
            field=models.CharField(default='21CS302'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reghistorym',
            name='cc7',
            field=models.CharField(default='21CS302'),
            preserve_default=False,
        ),
    ]
