# Generated by Django 5.0 on 2023-12-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0003_reghistorym_cc1_reghistorym_cc2_reghistorym_cc3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reghistorym',
            name='sec1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reghistorym',
            name='sec2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reghistorym',
            name='sec3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reghistorym',
            name='sec4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reghistorym',
            name='sec5',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reghistorym',
            name='sec6',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reghistorym',
            name='sec7',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
