# Generated by Django 5.0 on 2024-01-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0005_feedbackposted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackposted',
            old_name='faculty',
            new_name='fid',
        ),
        migrations.RemoveField(
            model_name='feedbackposted',
            name='ctitle',
        ),
        migrations.RemoveField(
            model_name='feedbackposted',
            name='sname',
        ),
    ]
