# Generated by Django 5.0 on 2024-01-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0006_rename_faculty_feedbackposted_fid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackposted',
            name='sid',
            field=models.BigIntegerField(),
        ),
    ]
