# Generated by Django 5.0 on 2024-02-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0007_alter_feedbackposted_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reghistorym',
            name='cc2',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='cc3',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='cc4',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='cc5',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='cc6',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='cc7',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='f2',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='f3',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='s2',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='s3',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='sec2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='sec3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='sec4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='sec5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='sec6',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='sec7',
            field=models.IntegerField(null=True),
        ),
    ]
