# Generated by Django 5.0 on 2024-04-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0008_alter_reghistorym_cc2_alter_reghistorym_cc3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regm',
            name='access',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
