# Generated by Django 5.0 on 2024-05-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0009_regm_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='regm',
            name='pgm',
            field=models.CharField(choices=[('BTECH', 'BTECH'), ('MTECH', 'MTECH')], default='BTECH'),
            preserve_default=False,
        ),
    ]
