# Generated by Django 5.0 on 2024-06-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0010_regm_pgm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackposted',
            name='q1',
            field=models.CharField(default='Is the syllabus coverage matching with the lesson plan as on date?', editable=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='feedbackposted',
            name='q2',
            field=models.CharField(default='How well is the teacher able to explain the concept?', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='feedbackposted',
            name='q3',
            field=models.CharField(default='Is the teacher encouraging interaction to get the doubts clarified?', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='feedbackposted',
            name='q4',
            field=models.CharField(default='Whether your teacher is teaching in any other language than English?', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='feedbackposted',
            name='q5',
            field=models.CharField(default='Overall rating of your teacher.', editable=False, max_length=100),
        ),
    ]
