# Generated by Django 5.0 on 2024-06-17 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_faculty_cur_ay_faculty_cur_sem_faculty_resume'),
        ('regapp', '0012_alter_feedbackposted_q1_alter_feedbackposted_q2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reghistorym',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.student'),
        ),
    ]
