# Generated by Django 5.0 on 2024-06-22 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_facultycoursemapping_component'),
        ('regapp', '0013_alter_reghistorym_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reghistorym',
            name='f1',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='f2',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='f3',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='f4',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='f5',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='f6',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='f7',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='s1',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='s2',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='s3',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='s4',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='s5',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='s6',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='s7',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='sec1',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='sec2',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='sec3',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='sec4',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='sec5',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='sec6',
        ),
        migrations.RemoveField(
            model_name='reghistorym',
            name='sec7',
        ),
        migrations.AddField(
            model_name='reghistorym',
            name='fcm1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='map1', to='adminapp.facultycoursemapping'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reghistorym',
            name='fcm2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='map2', to='adminapp.facultycoursemapping'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reghistorym',
            name='fcm3',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='map3', to='adminapp.facultycoursemapping'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reghistorym',
            name='fcm4',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='map4', to='adminapp.facultycoursemapping'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reghistorym',
            name='fcm5',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='map5', to='adminapp.facultycoursemapping'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reghistorym',
            name='fcm6',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='map6', to='adminapp.facultycoursemapping'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reghistorym',
            name='fcm7',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='map7', to='adminapp.facultycoursemapping'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='cc1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course1', to='adminapp.course'),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='cc2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course2', to='adminapp.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='cc3',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course3', to='adminapp.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='cc4',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course4', to='adminapp.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='cc5',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course5', to='adminapp.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='cc6',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course6', to='adminapp.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='cc7',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course7', to='adminapp.course'),
            preserve_default=False,
        ),
    ]
