# Generated by Django 5.0 on 2024-06-22 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_facultycoursemapping_component'),
        ('regapp', '0014_remove_reghistorym_f1_remove_reghistorym_f2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reghistorym',
            name='cc1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course1', to='adminapp.course'),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='cc2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course2', to='adminapp.course'),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='cc3',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course3', to='adminapp.course'),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='cc4',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course4', to='adminapp.course'),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='cc5',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course5', to='adminapp.course'),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='cc6',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course6', to='adminapp.course'),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='cc7',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course7', to='adminapp.course'),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='fcm1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='map1', to='adminapp.facultycoursemapping'),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='fcm2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='map2', to='adminapp.facultycoursemapping'),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='fcm3',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='map3', to='adminapp.facultycoursemapping'),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='fcm4',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='map4', to='adminapp.facultycoursemapping'),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='fcm5',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='map5', to='adminapp.facultycoursemapping'),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='fcm6',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='map6', to='adminapp.facultycoursemapping'),
        ),
        migrations.AlterField(
            model_name='reghistorym',
            name='fcm7',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='map7', to='adminapp.facultycoursemapping'),
        ),
    ]
