from django import forms
from .models import Faculty, Student, FacultyCourseMapping

class AddFacultyForm(forms.ModelForm):
    class Meta:
        model = Faculty # model name
        fields = "__all__" # all fields except autogenerated
        exclude = {"password"} #to exclude displaying password field, , "qualification" to add it
        labels = {"facultyid":"Enter Faculty Id", "fullname":"Enter Full Name"} # to change labels

class AddStudentForm(forms.ModelForm):
    class Meta:
        model=Student
        fields="__all__"
        labels ={"studentid": "Give Student Id", "fullname":"Full Name"}


class StudentUpdateForm(forms.ModelForm):
    class Meta:
        model=Student
        fields="__all__"
        exclude={"studentid"}


class FacultyUpdateForm(forms.ModelForm):
    class Meta:
        model=Faculty
        fields="__all__"
        exclude={"facultyid"}

class FacultyCourseMappingForm(forms.ModelForm):
    class Meta:
        model=FacultyCourseMapping
        fields="__all__"