from django import forms
from .models import Faculty, Student, FacultyCourseMapping,Grievance

class AddFacultyForm(forms.ModelForm):
    class Meta:
        model = Faculty # model name
        fields = "__all__" # all fields except autogenerated
        exclude = {"password"} #to exclude displaying password field, , "qualification" to add it
        labels = {"facultyid":"Enter Faculty Id", "fullname":"Enter Full Name", "gracceess":"Access to Grievances", "flag":"Access to their Account", "access":"Sub-Admin Access","ay":"Academic Year", "graccess":"Greivance Access"} # to change labels

class AddStudentForm(forms.ModelForm):
    class Meta:
        model=Student
        fields="__all__"
        labels ={"studentid": "Give Student Id ", "fullname":"Full Name ", "ay":"Academic Year Joining ","cur_ay":"Current Academic Year ", "cur_yr":"Current Year ","cur_sem":"Current Semester" }



class StudentUpdateForm(forms.ModelForm):
    class Meta:
        model=Student
        fields="__all__"
        exclude={"studentid", "password"}
        labels = {"fullname": "Full Name ", "ay": "Academic Year Joining ",
                  "cur_ay": "Current Academic Year ", "cur_yr": "Current Year ", "cur_sem": "Current Semester"}


class FacultyUpdateForm(forms.ModelForm):
    class Meta:
        model=Faculty
        fields="__all__"
        exclude={"facultyid", "password"}
        labels = {"fullname": "Full Name ", "ay": "Academic Year Joining ",
                  "cur_ay": "Current Academic Year ", "cur_yr": "Current Year ", "cur_sem": "Current Semester", "graccess":"GrievancesViewAccess", "access":"Access", "flag":"SelfAccountAccess"}


class FacultyCourseMappingForm(forms.ModelForm):
    class Meta:
        model=FacultyCourseMapping
        fields="__all__"

    def __init__(self, *args, **kwargs):
        super(FacultyCourseMappingForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class GrievanceForm(forms.ModelForm):
    class Meta:
        model=Grievance
        fields ="__all__"
        exclude={"pid", "prgm", "dept", "ay", "sem", "date", "status", "solved", "email", "solvedby", "name"}

    def __init__(self, *args, **kwargs):
        super(GrievanceForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'