# Generated by Django 5.0 on 2023-12-27 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'admin_table',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE')], max_length=30)),
                ('program', models.CharField(choices=[('BTECH', 'BTECH'), ('MTECH', 'MTECH')], max_length=100)),
                ('academicyear', models.CharField(choices=[('2023-2024', '2023-2024'), ('2022-2023', '2022-2023')], max_length=30)),
                ('semester', models.CharField(choices=[('ODD', 'ODD'), ('EVEN', 'EVEN')], max_length=10)),
                ('year', models.IntegerField()),
                ('coursecode', models.CharField(max_length=100)),
                ('coursetitle', models.CharField(max_length=100)),
                ('ltps', models.CharField(max_length=10)),
                ('credits', models.FloatField()),
            ],
            options={
                'db_table': 'course_table',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyid', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=20)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE')], max_length=30)),
                ('qualification', models.CharField(choices=[('PHD', 'PHD'), ('MTECH', 'MTECH')], max_length=100)),
                ('designation', models.CharField(choices=[('Prof.', 'Professor'), ('Assoc. Prof', 'Associate Professor'), ('Asst. Prof', 'Assistant Professor')], max_length=100)),
                ('password', models.CharField(default='klu123', max_length=30)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'faculty_table',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=20)),
                ('ay', models.CharField(max_length=10)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE')], max_length=30)),
                ('program', models.CharField(choices=[('BTECH', 'BTECH'), ('MTECH', 'MTECH')], max_length=100)),
                ('year', models.IntegerField()),
                ('semester', models.CharField(choices=[('ODD', 'ODD'), ('EVEN', 'EVEN')], max_length=10)),
                ('password', models.CharField(default='klu123', max_length=30)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=10, unique=True)),
                ('cur_ay', models.CharField(max_length=10)),
                ('cur_yr', models.IntegerField()),
                ('cur_sem', models.CharField(choices=[('ODD', 'ODD'), ('EVEN', 'EVEN')], max_length=10)),
            ],
            options={
                'db_table': 'student_table',
            },
        ),
        migrations.CreateModel(
            name='FacultyCourseMapping',
            fields=[
                ('mappingid', models.AutoField(primary_key=True, serialize=False)),
                ('component', models.CharField(choices=[('L', 'Lecture'), ('T', 'Tutorial'), ('P', 'Practical'), ('S', 'Skill')])),
                ('type', models.BooleanField(verbose_name='Faculty Type(CC/Instructor)')),
                ('section', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.faculty')),
            ],
            options={
                'db_table': 'facultycousemapping_table',
            },
        ),
    ]
