# Generated by Django 5.0 on 2024-02-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='ay',
            field=models.CharField(default='0'),
            preserve_default=False,
        ),
    ]
