# Generated by Django 5.0 on 2024-05-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_faculty_ay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cur_yr',
            field=models.IntegerField(default=1),
        ),
    ]
