# Generated by Django 5.0 on 2024-06-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_student_cur_yr'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='cur_ay',
            field=models.CharField(default='2023-2024'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='cur_sem',
            field=models.CharField(choices=[('ODD', 'ODD'), ('EVEN', 'EVEN')], default='ODD', max_length=10),
        ),
        migrations.AddField(
            model_name='faculty',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume/'),
        ),
    ]
