# Generated by Django 5.0 on 2024-06-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_faculty_cur_ay_faculty_cur_sem_faculty_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
