# Generated by Django 5.0 on 2024-06-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_faculty_email_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='facultyid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
