# Generated by Django 5.0 on 2024-06-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_facultycoursemapping_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='access',
            field=models.BooleanField(default=0),
        ),
    ]
