# Generated by Django 5.0 on 2024-06-25 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_faculty_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='access',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
