# Generated by Django 5.0 on 2024-06-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_faculty_flag_student_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(blank=True, max_length=40),
        ),
    ]
