# Generated by Django 5.0 on 2024-06-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_admin_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('category', models.CharField(choices=[('Hostel', 'Hostel'), ('Transport', 'Transport'), ('Internet', 'Internet'), ('Counselling', 'Counselling'), ('ClassroomMaintanance', 'ClassroomMaintanance'), ('OtherIssues', 'OtherIssues')])),
                ('issue', models.CharField()),
            ],
            options={
                'db_table': 'grievance_table',
            },
        ),
    ]
