# Generated by Django 5.0 on 2024-07-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_grievance'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='ay',
            field=models.CharField(default='2023-2024'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grievance',
            name='dept',
            field=models.CharField(default='CSE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grievance',
            name='prgm',
            field=models.CharField(default='B.TECH'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grievance',
            name='sem',
            field=models.CharField(default='ODD'),
            preserve_default=False,
        ),
    ]
