# Generated by Django 5.0 on 2024-07-02 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_grievance_ay_grievance_dept_grievance_prgm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
