# Generated by Django 5.0 on 2024-07-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_grievance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grievance',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
