# Generated by Django 5.0 on 2024-07-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_grievance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='prgm',
            field=models.CharField(blank=True),
        ),
    ]
