# Generated by Django 5.0 on 2024-07-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_alter_grievance_prgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
