# Generated by Django 5.0 on 2024-07-03 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_grievance_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='graccess',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
