# Generated by Django 5.0 on 2024-07-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_faculty_graccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='solvedby',
            field=models.IntegerField(default=0),
        ),
    ]
